catalog/urls.py
from django.urls import path
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    url(r'borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
    url(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
    url(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
    url(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
    url(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
]

local_library/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid
from datetime import date

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

LOAN_STATUS = (
    ('m', 'Maintenance'),
    ('o', 'On loan'),
    ('a', 'Available'),
    ('r', 'Reserved'),
)


class BookLanguage(models.Model):
    """
    Модель языка книги
    """
    name = models.CharField(max_length=100, help_text="Введите язык")
    
    def __str__(self):
        """
        Представление модели в виде строки
        """
        return self.name


class BookGenre(models.Model):
    """
    Модель книжного жанра
    """
    name = models.CharField(max_length=200, help_text="Введите жанр книги")
    
    def __str__(self):
        """
        Представление модели в виде строки
        """
        return self.name


class Author(models.Model):
    """
    Модель автора
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Умер', null=True, blank=True)
    
    def get_absolute_url(self):
        """
        Возвращает URL для доступа к конкретного автора.
        """
        return reverse('author-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        Представление модели в виде строки
        """
        return f"{self.first_name} {self.last_name}"
    

    def str_for_list_view(self):
        return f"{self.first_name} {self.last_name} {self.str_date()}"
    

    def str_date(self):
        return f"({self.date_of_birth} - {self.date_of_death if not self.date_of_death is None else ''})" 


class Book(models.Model):
    """
    Модель книги
    """
    title = models.CharField(max_length=200)
    author = models.ManyToManyField(Author, help_text="Выбрать автора")
    summary = models.TextField(max_length=1000, help_text="Введите краткое описание книги")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(BookGenre, help_text="Выбрать жанр")
    language = models.ManyToManyField(BookLanguage, help_text="Выбрать язык")
    
    def __str__(self):
        """
        Представление модели в виде строки
        """
        return self.title
    
    
    def get_absolute_url(self):
        """
        Возвращает URL для доступа к конкретной книге.
        """
        return reverse('book-detail', args=[str(self.id)])


    def display_author(self):
        """
        Создать строковое представление для авторов. Ипользуется для отображения авторов в админке.
        """
        authors = self.author.all()
        print(authors)
        return ', '.join([str(author) for author in authors[:3]]) + (', ...' if len(authors) > 3 else '')
    display_author.short_description = 'Author'


    def display_genre(self):
        """
        Создать строковое представление для жанра. Ипользуется для отображения жанра в админке.
        """
        genres = self.genre.all()
        return ', '.join([genre.name for genre in genres[:3]]) + (', ...' if len(genres) > 3 else '')
    display_genre.short_description = 'Genre'


    def count_instanses(self):
        return len(self.bookinstance_set.all())


class BookInstance(models.Model):
    """
    Модель экземпляра книги
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Уникальный ID для конкретного экземпляра книги в данной библиотеке")
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Доступность книги')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)


    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
        

    def __str__(self):
        """
        String for representing the Model object
        """
        return f"{self.id} ({self.book.title})"

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.
    
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Введите дату между сегоднящним днем и 4 неделями вперед (по-умолчанию 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        #Проверка того, что дата не выходит за "нижнюю" границу (не в прошлом). 
        if data < datetime.date.today():
            raise ValidationError(_('Неверная дата - дата возврата в прошлом'))

        #Проверка того, то дата не выходит за "верхнюю" границу (+4 недели).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Неверная дата - дата возврата установлена позже чем 4 недели вперед'))

        # Помните, что всегда надо возвращать "очищенные" данные.
        return data

# то же самое
from django.forms import ModelForm
from .models import BookInstance

class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
       data = self.cleaned_data['due_back']
       
       #Проверка того, что дата не в прошлом
       if data < datetime.date.today():
           raise ValidationError(_('Invalid date - renewal in past'))

       #Check date is in range librarian allowed to change (+4 weeks)
       if data > datetime.date.today() + datetime.timedelta(weeks=4):
           raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

       # Не забывайте всегда возвращать очищенные данные
       return data

    class Meta:
        model = BookInstance
        fields = ['due_back',]
        labels = { 'due_back': _('Renewal date'), }
        help_texts = { 'due_back': _('Enter a date between now and 4 weeks (default 3).'), } 

catalog/views.py
import datetime

from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .forms import RenewBookForm
from . import models


def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    num_books = models.Book.objects.all().count()
    num_instances = models.BookInstance.objects.all().count()

    num_instances_available = models.BookInstance.objects.filter(status__exact='a').count()
    num_authors = models.Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    
    # Отрисовка HTML-шаблона index.html с данными внутри 
    # переменной контекста context
    return render(
        request,
        'index.html',
        context={
            'num_books': num_books,
            'num_instances': num_instances,
            'num_instances_available': num_instances_available,
            'num_authors': num_authors,
            'num_visits': num_visits
        },
    )


class BookListView(generic.ListView):
    model = models.Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = models.Book


class AuthorListView(generic.ListView):
    model = models.Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = models.Author


class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Generic class-based view listing books on loan to current user. 
    """
    model = models.BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return models.BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    """
    Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission.
    """
    model = models.BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return models.BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst=get_object_or_404(models.BookInstance, pk = pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})


class AuthorCreate(CreateView, PermissionRequiredMixin):
    model = models.Author
    fields = '__all__'

    permission_required = 'catalog.can_mark_returned'

class AuthorUpdate(UpdateView, PermissionRequiredMixin):
    model = models.Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']
    
    permission_required = 'catalog.can_mark_returned'

class AuthorDelete(DeleteView, PermissionRequiredMixin):
    model = models.Author
    success_url = reverse_lazy('authors')
    
    permission_required = 'catalog.can_mark_returned'


class BookCreate(CreateView, PermissionRequiredMixin):
    model = models.Book
    fields = '__all__'

    permission_required = 'catalog.can_mark_returned'

class BookUpdate(UpdateView, PermissionRequiredMixin):
    model = models.Book
    fields = ['title','author','summary','isbn','genre','language']
    
    permission_required = 'catalog.can_mark_returned'

class BookDelete(DeleteView, PermissionRequiredMixin):
    model = models.Book
    success_url = reverse_lazy('books')
    
    permission_required = 'catalog.can_mark_returned'

catalog/templates/catalog/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Author: {{ author }}</h1>

  <p> {{ author.str_date }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
    <b><a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.count_instanses}})</b>
    <p>{{ book.summary }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Author List</h1>
    {% if perms.catalog.can_mark_returned %} <a href="{% url 'author_create'%}">ADD NEW AUTHOR</a>  {% endif %}

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.str_for_list_view }}</a>
        {% if perms.catalog.can_mark_returned %} - <a href="{% url 'author_update' author.id %}">Edit</a>  {% endif %}
        {% if perms.catalog.can_mark_returned %} - <a href="{% url 'author_delete' author.id %}">Delete</a>  {% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no authors in the library.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> 
    {% for author in book.author.all %}
        <a href="{% url 'author-detail' author.pk %}">{{ author }}</a>
    {% endfor %}
  </p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if perms.catalog.can_mark_returned %} <a href="{% url 'book_create'%}">ADD NEW BOOK</a>  {% endif %}

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.display_author }})
        {% if perms.catalog.can_mark_returned %} - <a href="{% url 'book_update' book.id %}">Edit</a>  {% endif %}
        {% if perms.catalog.can_mark_returned %} - <a href="{% url 'book_delete' book.id %}">Delete</a>  {% endif %}
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base.html" %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) 
            {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %} 
            {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}